// weekly-report.mjs — assemble seo/reports/weekly-YYYY-MM-DD.md from the data layer.
// Reads the latest GSC pulls + changes-log.csv + crawl meta and computes:
//   - KPI deltas (aggregate + the top pages we edited)
//   - an EDITED vs CONTROL cohort read (the Gate-2 attribution method)
// Run after `gsc-pull` + a `crawl-audit`. If GSC is absent it still emits the
// structure with "gsc-pending" markers so the cadence is kept.
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..', '..');
const GSC = process.env.GSC_DIR || path.join(ROOT, 'seo/data/gsc');
const TODAY = new Date().toISOString().slice(0, 10);
const OUT = path.join(ROOT, 'seo/reports', `weekly-${TODAY}.md`);

function readCsv(file) {
  const p = path.join(GSC, file);
  if (!fs.existsSync(p)) return null;
  const lines = fs.readFileSync(p, 'utf8').trim().split('\n');
  const head = lines[0].split(',').map((s) => s.replace(/"/g, '').trim());
  const parse = (l) => { const o = []; let c = '', q = false; for (const ch of l) { if (ch === '"') q = !q; else if (ch === ',' && !q) { o.push(c); c = ''; } else c += ch; } o.push(c); return o.map((x) => x.trim().replace(/^"|"$/g, '')); };
  return lines.slice(1).map((l) => Object.fromEntries(head.map((h, i) => [h, parse(l)[i]])));
}

const metaPath = path.join(ROOT, 'seo/data/crawl/meta.json');
const meta = fs.existsSync(metaPath) ? JSON.parse(fs.readFileSync(metaPath, 'utf8')) : null;

const changes = fs.existsSync(path.join(ROOT, 'seo/data/changes-log.csv'))
  ? fs.readFileSync(path.join(ROOT, 'seo/data/changes-log.csv'), 'utf8').trim().split('\n').slice(1)
  : [];
const edited = new Set();
for (const line of changes) { const c = line.split(','); if (c[1]) edited.add(c[1].replace(/^"|"$/g, '')); }

const pages = readCsv('page.csv');
let agg = null, editedAgg = null, controlAgg = null;
if (pages) {
  const sum = (rows) => rows.reduce((a, r) => ({ imp: a.imp + (+r.impressions || 0), clk: a.clk + (+r.clicks || 0) }), { imp: 0, clk: 0 });
  agg = sum(pages);
  const inSitemap = (u) => (u.replace('https://www.marqly.com', '') || '/');
  editedAgg = sum(pages.filter((r) => edited.has(inSitemap(r.page))));
  controlAgg = sum(pages.filter((r) => !edited.has(inSitemap(r.page))));
}

const fmt = (n) => n == null ? '—' : n.toLocaleString('en-US');
const pct = (n) => n == null ? '—' : (n * 100).toFixed(2) + '%';

let md = `# Weekly SEO report — ${TODAY}\n\n`;
md += `> Generated by \`seo/scripts/weekly-report.mjs\`. GSC window is the last pull in \`seo/data/gsc/\`.\n\n`;
md += `## Data freshness\n`;
md += pages ? `- GSC pull present (${pages.length} page rows)\n` : `- GSC pull MISSING — run \`npm run seo:pull\` (blocked on the service-account property grant)\n`;
md += meta ? `- Crawl: ${meta.indexable} indexable / ${meta.total} URLs, ${new Date(meta.generatedAt).toISOString().slice(0, 10)}\n` : `- Crawl meta missing — run \`npm run seo:audit\`\n`;
md += `- changes-log rows: ${changes.length}; distinct edited URLs this program: ${edited.size}\n\n`;

md += `## KPI deltas (vs baseline in SEO-PROGRESS.md)\n`;
md += `| Metric | Now | Baseline | Delta |\n|---|---|---|---|\n`;
md += `| Indexable thin (<300) | ${meta ? meta.kpi.indexable_thin_lt300 : '—'} | 284 | ${meta ? meta.kpi.indexable_thin_lt300 - 284 : '—'} |\n`;
md += `| Localized stubs (<50% parity) | ${meta ? meta.kpi.localized_stubs_parity_lt50 : '—'} | 798 | ${meta ? meta.kpi.localized_stubs_parity_lt50 - 798 : '—'} |\n`;
md += `| Indexable URLs | ${meta ? meta.indexable : '—'} | 1914 | ${meta ? meta.indexable - 1914 : '—'} |\n`;
md += `| Titles >60 | ${meta ? meta.kpi.titles_over60 : '—'} | 550 | ${meta ? meta.kpi.titles_over60 - 550 : '—'} |\n\n`;

md += `## Edited-vs-control cohort (CTR, current window)\n`;
if (agg) {
  const ctr = (a) => a.imp ? a.clk / a.imp : 0;
  md += `| Cohort | Pages | Impressions | Clicks | CTR |\n|---|---|---|---|---|\n`;
  md += `| Edited by program | ${editedAgg ? pages.filter((r) => edited.has(r.page.replace('https://www.marqly.com', '') || '/')).length : 0} | ${fmt(editedAgg?.imp)} | ${fmt(editedAgg?.clk)} | ${pct(editedAgg && ctr(editedAgg))} |\n`;
  md += `| Control (untouched) | ${controlAgg ? pages.length - (editedAgg ? pages.filter((r) => edited.has(r.page.replace('https://www.marqly.com', '') || '/')).length : 0) : '—'} | ${fmt(controlAgg?.imp)} | ${fmt(controlAgg?.clk)} | ${pct(controlAgg && ctr(controlAgg))} |\n`;
  md += `| Whole site | ${pages.length} | ${fmt(agg.imp)} | ${fmt(agg.clk)} | ${pct(ctr(agg))} |\n\n`;
  md += `> GSC lags ~3 days; compare like-for-like windows once two pulls exist. Edit-date cohorting lives in changes-log.csv.\n`;
} else {
  md += `_Pending GSC pull._\n`;
}

fs.writeFileSync(OUT, md + '\n');
console.log(`wrote ${path.relative(ROOT, OUT)}`);
